# Generated by Django 3.1.3 on 2020-12-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('regno', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
